### ISSUE TITLE
Instantiate base model class in HF

### ISSUE THREAD

**Issue by pascalnotin** [OpenBioML/protein-lm-scaling#2]
Subclass the GPT2 HF class: https://huggingface.co/docs/transformers/model_doc/gpt2

**Comment by talkhanz** [comment]
Hey @pascalnotin this looks interesting. I can work on this! What is a higher priority? preprocessing the uniref50 set or this model? I can work on whichever you suggest

**Comment by pascalnotin** [comment]
Great, thanks @talkhanz ! Idea behind the first few issues posted in the task board is to instantiate a simple end-to-end pipeline that goes from 1) [pre-processing raw data](https://github.com/OpenBioML/protein-lm-scaling/issues/1), to 2) training a standard AR transformer on it (this issue), to 3)[evaluating on downstream task](https://github.com/OpenBioML/protein-lm-scaling/issues/4). 

The requirement for this issue here (step 2) would thus be to:
A- subclass the HF GPT2 class to a new class called say "APT" (Autoregressive Protein Transformer)
B- adapt it to handle AA sequences (eg., the GPT2config class since we will operate with a different vocab)
C- write a basic train script to train this model on the training data and evaluate on test data (only loss / perplexity tracking should be good for now)
D- persist intermediate (eg every 5k steps by default) and final checkpoints to disk

The issue focusing on [#3](https://github.com/OpenBioML/protein-lm-scaling/issues/4) will then take as input the trained model, and evaluate its performance.

I had done something similar when developing Tranception which may be helpful here (https://github.com/OATML-Markslab/Tranception/tree/main/tranception).

Let me know if any questions!

**Comment by talkhanz** [comment]
@pascalnotin thanks for getting in touch and sharing the cool details! I'll make an effort to have an update by our weekly call!

**Comment by cmvcordova** [comment]
Hey! How's this coming along? I'd love to help out.

**Comment by talkhanz** [comment]
> Hey! How's this coming along? I'd love to help out.

yes im in the middle of just finishing a colab notebook as proof of concept so a lending hand would be very handy (pun intended :P)

**Comment by justin-barton** [comment]
@talkhanz I'd be happy to help out as well if you'd like to share the colab link

**Comment by talkhanz** [comment]
let me tidy it a bit and ill share it very soon!

**Comment by talkhanz** [comment]
guys, you can find my colab [here](https://colab.research.google.com/drive/1Nx78Bv1VR9IKpGpa3pw_wdoYkY9IuG4Q?usp=sharing)

Since i didnt know what the preprocessed dataset would like, i tested my pipeline on [uniref50](https://huggingface.co/datasets/zpn/uniref50) alongside a random label vector. I had to use a tokenizer too (also the same as tranception,loaded from a file). This should easily be replaced by any other tokenizer we want (unless we want to preprocess the dataset from some other notebook) The dataset is being streamed using the datasets library (although there is an option to load from a file and convert the dataframe to Dataset class of huggingface) since the whole dataset is around (54gb). 

I think having a minimal preprocessed dataset would greatly help here because it will streamline how we organize our modelling notebook.  I should've asked this earlier!  

Also the model is identical to the tranception model for now (although im working on a simpler from the scratch GPT2 model).

@pascalnotin let me know your thoughts particularly if we should keep the model similar to Tranception or is a new model better? 

Also welcome feedback (& questions) from the rest of the people here!

**Comment by pascalnotin** [comment]
Closing this issue as features have all been instantiated in code. Thanks all
